---
title: "Sudoku Solver"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sudoku solver

### Creating the sudoku
```{r}
# A sudoku puzzle is:
  # A matrix with: 81 numbers read from top left -> bottom right by column
  #                9 rows & 9 columns
  #                    --> where 0 is any unfilled number
numbers <- c(1,0,7,0,0,9,0,2,0, #column 1
             8,0,0,0,0,0,0,0,7, #column 2
             0,0,0,0,1,0,0,0,0, #column 3
             0,0,1,6,0,7,0,0,5, #column 4
             0,2,0,0,0,0,6,3,0, #column 5
             0,0,9,0,0,5,0,0,2, #column 6
             4,0,0,0,0,0,0,0,0, #column 7
             0,0,3,0,0,1,5,0,0, #column 8
             0,0,0,0,3,0,0,0,8) #column 9
num_rows_and_columns <- 9

board <- matrix(numbers, num_rows_and_columns, num_rows_and_columns)
```

### Drawing the puzzle
```{r}
# Function to draw board
draw_board <- function(board, result = NULL, solved = FALSE) {
  # To draw the puzzle, use the plot function to outline the board
  plot(c(0,9), #x-coordinates
       c(0,9), #y-coordinates
       type="n", #leave as empty plot
       xlab = "", #no title for axis
       ylab = "", #no title for axis
       main = "", #no title for board
       xaxt="n", #no scale on axis
       yaxt="n", #no scale on axis
       bty="n", #no box around plot
       asp = 1) #need to be a square object
  
  # Then draw each individual box
  for (column_number in 1:9) {
    for (row_number in 1:9) {
      rect(column_number - 1,
           row_number - 1,
           column_number,
           row_number) #creating individual boxes for each number
      
      if (board[10-row_number,column_number] != 0) { #if the number is not 0, ie if box is not empty
        text((column_number - 1) + 0.5, #center of box by height
              (row_number - 1) + 0.5, #center of box by width
              (((board[10-row_number,column_number])))) #write the number
      }
      if (solved) {
        text((column_number - 1) + 0.5,
             (row_number - 1) + 0.5,
             (((result[10 - row_number,column_number]))))
      }
    }
  }
  
  # Then draw the larger cages
  for(large_square_width in 1:3) {
    for(large_square_height in 1:3) {
      rect((large_square_width - 1) * 3,
           (large_square_height - 1) * 3,
           large_square_width * 3,
           large_square_height * 3,
           lwd=2) #draw larger boxes slightly thicker (for each 3x3 block)
    }
  }
}
```

```{r}
#Drawing the board
draw_board(board)
```


### Functions to solve the puzzle
```{r}
# Find empty cells (boxes to solve)
empty_cells <- function(board) {
  which(board == 0, arr.ind = TRUE)
}
```

```{r}
# Function to check if a number can be placed in a box
valid_number <- function(board, test_number, row, column) {
  
  # Check if any box in the same row has the same value
  if (any(board[row,] == test_number)) {
    return(FALSE)
  }
  
  # Check if any box in the same column has the same value
  if(any(board[,column] == test_number)) {
    return(FALSE)
  }
  
  # Check if any box in the same 3x3 cage has the same value
  large_box_index_width <- floor((row - 1) / 3) + 1
  large_box_index_height <- floor((column - 1) / 3) + 1
  
  large_box <- board[((3 * large_box_index_width) - 2):(3 * large_box_index_width), #take slice of 3 rows
               ((3 * large_box_index_height) - 2):(3 * large_box_index_height)] #take slice of 3 columns
  if(any(large_box == test_number)) {
    return(FALSE)
  }
  
  # If none conditions are met, number is potentially valid
  return(TRUE)
}
```

```{r}
# Make copy of board - to print when solved
result <- board
```

```{r}
# Solving the puzzle
solver <- function(board, needed_cells = NULL, index = 1)
{
  # Find all empty cells
  if (is.null(needed_cells)) {
    needed_cells <- empty_cells(board)
  }
  
  # Base condition - puzzle is solved
  if (index > nrow(needed_cells)) {
    result <<- board
    return(TRUE)
  }
  
  # Recursive condition - puzzle is unsolved
  else {
    row_number <- needed_cells[index, 1]
    column_number <- needed_cells[index, 2]
  }
  
  
  for (test_number in 1:9) {
    if(!valid_number(board, test_number, row_number, column_number)) {
      next
    }
    
    else {
      board_copy = board
      board_copy[row_number, column_number] <- test_number
      if(solver(board_copy, needed_cells, index + 1)) {
        return(TRUE)
      }
    }
  }
  
  # If puzzle is not solvable, return FALSE
  return(FALSE)
}
```

### Solving the puzzle
```{r}
# Invisible to ignore any output messages
invisible(solver(board))
```

### Printing solution
```{r}
# As before
draw_board(board, result = result, solved = TRUE)
```